# Site settings
title: 차현진 블로그
email:
description: > # this means to ignore newlines until "baseurl:"
  저엔트로피를 지향하는 개발자
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gumpcha.github.io" # the base hostname & protocol for your site
twitter_username: gumpcha
github_username:  gumpcha

# Outputting
permalink: /blog/:title

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["autolink"]

exclude: [publish.sh]
